workaround jdk26 on el7 missing /lib64/libm.so.6
todo: decide whether to applly this at all
and if so then (jdk26+el7 container only?)
Build origin only fedora, or also devkit based?

as tester
Error: dl failure on line 532
Error: failed /hell/lib/server/libjvm.so, because /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /hell/lib/server/libjvm.so)
Error: building at STEP "RUN a=0; sudo useradd tester || a=$? ; if [ $a -eq 0 ] ; then echo "as tester" && su tester -c "DISPLAY=:0 /hell/bin/java -m helloworld" ; else echo "as $(whoami)" && bash -c "DISPLAY=:0 /hell/bin/java -m helloworld" ; fi": while running runtime: exit status 6